# Generated by Django 2.2.4 on 2019-08-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=60)),
                ('company_api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('driver_name', models.CharField(max_length=20)),
                ('driver_lastname', models.CharField(max_length=20)),
                ('driver_phone', models.CharField(max_length=20)),
                ('driver_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField()),
                ('unit_number', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_vin', models.CharField(max_length=60)),
                ('unit_plate', models.CharField(max_length=10)),
                ('unit_eld', models.CharField(max_length=30)),
                ('unit_active', models.BooleanField()),
                ('unit_ifta', models.BooleanField()),
                ('unit_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Company')),
            ],
        ),
    ]
