# Generated by Django 2.2.4 on 2019-09-01 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(editable=False, null=True, unique=True)),
                ('company_name', models.CharField(max_length=60)),
                ('company_address', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(editable=False, help_text="Driver's id in KeepTruckin system", null=True, unique=True)),
                ('driver_name', models.CharField(help_text='Name of the driver', max_length=20)),
                ('driver_lastname', models.CharField(help_text='Last name of the driver', max_length=20)),
                ('driver_phone', models.CharField(help_text="Driver's phone number", max_length=20, null=True)),
                ('driver_status', models.CharField(default='active', help_text='Indicates if the driver is active or deactivated', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(editable=False, help_text="Unit's id in KeepTruckin system", null=True, unique=True)),
                ('unit_number', models.IntegerField(help_text='Internal number of the truck in the company', unique=True)),
                ('unit_eld', models.CharField(help_text='Id of the ELD device installed on the unit', max_length=30, null=True)),
                ('unit_active', models.BooleanField(help_text='Indicates if the unit is used by the company')),
                ('unit_ifta', models.BooleanField(help_text='Indicates if the unit is IFTA convenient', null=True)),
                ('unit_type', models.CharField(help_text='Group of units', max_length=30, null=True)),
                ('unit_company', models.ForeignKey(help_text='Links to the company, unit belongs to', on_delete=django.db.models.deletion.CASCADE, to='Core.Company')),
                ('unit_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
