# Generated by Django 2.2.4 on 2019-08-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20190823_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_api_key',
        ),
    ]
