# Generated by Django 2.2.4 on 2019-08-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_company_company_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_active',
            field=models.BooleanField(help_text='Indicates if the driver is working at the company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.IntegerField(help_text="Driver's id in KeepTruckin system"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_lastname',
            field=models.CharField(help_text='Last name of the driver', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(help_text='Name of the driver', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_phone',
            field=models.CharField(help_text="Driver's phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_active',
            field=models.BooleanField(help_text='Indicates if the unit is used by the company'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_company',
            field=models.ForeignKey(help_text='Links to the company, unit belongs to', on_delete=django.db.models.deletion.CASCADE, to='Core.Company'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_eld',
            field=models.CharField(help_text='Id of the ELD device installed on the unit', max_length=30),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(help_text="Unit's id in KeepTruckin system"),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_ifta',
            field=models.BooleanField(help_text='Indicates if the unit is IFTA convenient'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.IntegerField(help_text='Internal number of the truck in the company', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_plate',
            field=models.CharField(help_text='Plate numer of the unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_vin',
            field=models.CharField(help_text='Vin number of the unit', max_length=60),
        ),
    ]
