# Generated by Django 2.2.4 on 2019-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20190824_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.IntegerField(help_text="Driver's id in KeepTruckin system", unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(help_text="Unit's id in KeepTruckin system", unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.IntegerField(help_text='Internal number of the truck in the company', primary_key=True, serialize=False, unique=True),
        ),
    ]
