# Generated by Django 2.2.4 on 2019-08-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20190826_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.IntegerField(editable=False, help_text="Driver's id in KeepTruckin system", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(editable=False, help_text="Unit's id in KeepTruckin system", null=True, unique=True),
        ),
    ]
