# Generated by Django 2.2.4 on 2019-08-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20190826_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
