# Generated by Django 2.2.4 on 2019-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_unit_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='staff',
            new_name='unit_staff',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_plate',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_vin',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
