# Generated by Django 2.2.4 on 2019-09-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the report')),
                ('end_date', models.DateField(help_text='Ending date of the report')),
                ('truck', models.ForeignKey(help_text='Link to the related unit(vehicle) data', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_name', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', ' OH'), ('OK', ' OK'), ('OR', ' OR'), ('PA', ' PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY'), ('AB', 'AB (Canada)'), ('BC', 'BC (Canada)'), ('MB', 'MB (Canada)'), ('NB', 'NB (Canada)'), ('NL', 'NL (Canada)'), ('NT', 'NT (Canada)'), ('NS', 'NS (Canada)'), ('NU', 'NU (Canada)'), ('ON', 'ON (Canada)'), ('PE', 'PE (Canada)'), ('QC', 'QC (Canada)'), ('SK', 'SK (Canada)'), ('YT', 'YT (Canada)')], help_text='Jurisdiction abbreviation', max_length=10)),
                ('miles', models.PositiveIntegerField(help_text='Total miles in jurisdiction')),
                ('report', models.ForeignKey(help_text='Link to the related report data', on_delete=django.db.models.deletion.CASCADE, to='Reporting.Total_Report')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date (mm/dd/yyyy)')),
                ('jurisdiction', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', ' OH'), ('OK', ' OK'), ('OR', ' OR'), ('PA', ' PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY'), ('AB', 'AB (Canada)'), ('BC', 'BC (Canada)'), ('MB', 'MB (Canada)'), ('NB', 'NB (Canada)'), ('NL', 'NL (Canada)'), ('NT', 'NT (Canada)'), ('NS', 'NS (Canada)'), ('NU', 'NU (Canada)'), ('ON', 'ON (Canada)'), ('PE', 'PE (Canada)'), ('QC', 'QC (Canada)'), ('SK', 'SK (Canada)'), ('YT', 'YT (Canada)')], help_text='Jurisdiction abbreviation', max_length=10)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'diesel'), ('Gasoline', 'gasoline')], default='diesel', help_text='Fuel type (diesel by default)', max_length=20)),
                ('total_cost', models.FloatField(help_text='Cost of bought fuel')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], default='USD', help_text='Currency (US dollar by default)', max_length=5)),
                ('fuel_amount', models.FloatField(help_text='Volume of fuel bought')),
                ('fuel_unit', models.CharField(choices=[('gal', 'gallons'), ('ltr', 'liters')], default='gal', help_text='Volume measurement (gallons by default)', max_length=10)),
                ('ref_no', models.CharField(blank=True, help_text='Invoice number', max_length=15)),
                ('vendor', models.CharField(help_text='Truck stop name', max_length=40)),
                ('odometer', models.IntegerField(blank=True, help_text='Odometer reading on arrival to the truck stop')),
                ('odometer_unit', models.CharField(blank=True, choices=[('km', 'kilometers'), ('mi', 'miles')], help_text='Distance measurement', max_length=5)),
                ('driver', models.ForeignKey(help_text='Link to related the driver data', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Driver')),
                ('truck', models.ForeignKey(help_text='Link to the related unit(vehicle) data', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Unit')),
            ],
        ),
    ]
