# Generated by Django 2.2.4 on 2019-08-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0004_auto_20190824_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date (mm-dd-yyyy)')),
                ('start_odometer', models.PositiveIntegerField(help_text='Odometer reading on the start of the day')),
                ('end_odometer', models.PositiveIntegerField(help_text='Odometer reading on the end of the day')),
                ('miles', models.PositiveIntegerField(help_text='Total miles this day according to odometers difference')),
                ('driver', models.ForeignKey(help_text='Link to related the driver data', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Driver')),
                ('truck', models.ForeignKey(help_text='Link to the related unit(vehicle) data', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the report')),
                ('end_date', models.DateField(help_text='Ending date of the report')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_name', models.CharField(choices=[('AB', 'Alberta AB'), ('BC', 'British Columbia BC'), ('MB', 'Manitoba MB'), ('NB', 'New Brunswick NB'), ('NL', 'Newfoundland and Labrador NL'), ('NT', 'Northwest Territories NT'), ('NS', 'Nova Scotia NS'), ('NU', 'Nunavut NU'), ('ON', 'Ontario ON'), ('PE', 'Prince Edward Island PE'), ('QC', 'Quebec QC'), ('SK', 'Saskatchewan SK'), ('YT', 'Yukon YT'), ('AL', 'Alabama AL'), ('AK', 'Alaska AK'), ('AZ', 'Arizona AZ'), ('AR', 'Arkansas AR'), ('CA', 'California CA'), ('CO', 'Colorado CO'), ('CT', 'Connecticut CT'), ('DE', 'Delaware DE'), ('DC', 'District Columbia DC'), ('FL', 'Florida FL'), ('GA', 'Georgia GA'), ('ID', 'Idaho ID'), ('IL', 'Illinois IL'), ('IN', 'Indiana IN'), ('IA', 'Iowa IA'), ('KS', 'Kansas KS'), ('KY', 'Kentucky KY'), ('LA', 'Louisiana LA'), ('ME', 'Maine ME'), ('MD', 'Maryland MD'), ('MA', 'Massachusetts MA'), ('MI', 'Michigan MI'), ('MN', 'Minnesota MN'), ('MS', 'Mississippi MS'), ('MO', 'Missouri MO'), ('MT', 'Montana MT'), ('NE', 'Nebraska NE'), ('NV', 'Nevada NV'), ('NH', 'New Hampshire NH'), ('NJ', 'New Jersey NJ'), ('NM', 'New Mexico NM'), ('NY', 'New York NY'), ('NC', 'North Carolina NC'), ('ND', 'North Dakota ND'), ('OH', 'Ohio OH'), ('OK', 'Oklahoma OK'), ('OR', 'Oregon OR'), ('PA', 'Pennsylvania PA'), ('RI', 'Rhode Island RI'), ('SC', 'South Carolina SC'), ('SD', 'South Dakota SD'), ('TN', 'Tennessee TN'), ('TX', 'Texas TX'), ('UT', 'Utah UT'), ('VT', 'Vermont VT'), ('VA', 'Virginia VA'), ('WA', 'Washington WA'), ('WV', 'West Virginia WV'), ('WI', 'Wisconsin WI'), ('WY', 'Wyoming WY')], help_text='Jurisdiction abbreviation', max_length=10)),
                ('start_odometer', models.PositiveIntegerField(help_text='Odometer reading when entering jurisdiction')),
                ('end_odometer', models.PositiveIntegerField(help_text='Odometer reading when exiting jurisdiction')),
                ('miles', models.PositiveIntegerField(help_text='Total miles in jurisdiction according to Keep Trucking data')),
                ('location_date', models.ForeignKey(help_text='Link to a related date', on_delete=django.db.models.deletion.CASCADE, to='Reporting.Daily_Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_name', models.CharField(choices=[('AB', 'Alberta AB'), ('BC', 'British Columbia BC'), ('MB', 'Manitoba MB'), ('NB', 'New Brunswick NB'), ('NL', 'Newfoundland and Labrador NL'), ('NT', 'Northwest Territories NT'), ('NS', 'Nova Scotia NS'), ('NU', 'Nunavut NU'), ('ON', 'Ontario ON'), ('PE', 'Prince Edward Island PE'), ('QC', 'Quebec QC'), ('SK', 'Saskatchewan SK'), ('YT', 'Yukon YT'), ('AL', 'Alabama AL'), ('AK', 'Alaska AK'), ('AZ', 'Arizona AZ'), ('AR', 'Arkansas AR'), ('CA', 'California CA'), ('CO', 'Colorado CO'), ('CT', 'Connecticut CT'), ('DE', 'Delaware DE'), ('DC', 'District Columbia DC'), ('FL', 'Florida FL'), ('GA', 'Georgia GA'), ('ID', 'Idaho ID'), ('IL', 'Illinois IL'), ('IN', 'Indiana IN'), ('IA', 'Iowa IA'), ('KS', 'Kansas KS'), ('KY', 'Kentucky KY'), ('LA', 'Louisiana LA'), ('ME', 'Maine ME'), ('MD', 'Maryland MD'), ('MA', 'Massachusetts MA'), ('MI', 'Michigan MI'), ('MN', 'Minnesota MN'), ('MS', 'Mississippi MS'), ('MO', 'Missouri MO'), ('MT', 'Montana MT'), ('NE', 'Nebraska NE'), ('NV', 'Nevada NV'), ('NH', 'New Hampshire NH'), ('NJ', 'New Jersey NJ'), ('NM', 'New Mexico NM'), ('NY', 'New York NY'), ('NC', 'North Carolina NC'), ('ND', 'North Dakota ND'), ('OH', 'Ohio OH'), ('OK', 'Oklahoma OK'), ('OR', 'Oregon OR'), ('PA', 'Pennsylvania PA'), ('RI', 'Rhode Island RI'), ('SC', 'South Carolina SC'), ('SD', 'South Dakota SD'), ('TN', 'Tennessee TN'), ('TX', 'Texas TX'), ('UT', 'Utah UT'), ('VT', 'Vermont VT'), ('VA', 'Virginia VA'), ('WA', 'Washington WA'), ('WV', 'West Virginia WV'), ('WI', 'Wisconsin WI'), ('WY', 'Wyoming WY')], help_text='Jurisdiction abbreviation', max_length=10)),
                ('miles', models.PositiveIntegerField(help_text='Total miles in jurisdiction')),
                ('report', models.ForeignKey(help_text='Link to the related report data', on_delete=django.db.models.deletion.CASCADE, to='Reporting.Total_Report')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date (mm-dd-yyyy)')),
                ('jurisdiction', models.CharField(choices=[('AB', 'Alberta AB'), ('BC', 'British Columbia BC'), ('MB', 'Manitoba MB'), ('NB', 'New Brunswick NB'), ('NL', 'Newfoundland and Labrador NL'), ('NT', 'Northwest Territories NT'), ('NS', 'Nova Scotia NS'), ('NU', 'Nunavut NU'), ('ON', 'Ontario ON'), ('PE', 'Prince Edward Island PE'), ('QC', 'Quebec QC'), ('SK', 'Saskatchewan SK'), ('YT', 'Yukon YT'), ('AL', 'Alabama AL'), ('AK', 'Alaska AK'), ('AZ', 'Arizona AZ'), ('AR', 'Arkansas AR'), ('CA', 'California CA'), ('CO', 'Colorado CO'), ('CT', 'Connecticut CT'), ('DE', 'Delaware DE'), ('DC', 'District Columbia DC'), ('FL', 'Florida FL'), ('GA', 'Georgia GA'), ('ID', 'Idaho ID'), ('IL', 'Illinois IL'), ('IN', 'Indiana IN'), ('IA', 'Iowa IA'), ('KS', 'Kansas KS'), ('KY', 'Kentucky KY'), ('LA', 'Louisiana LA'), ('ME', 'Maine ME'), ('MD', 'Maryland MD'), ('MA', 'Massachusetts MA'), ('MI', 'Michigan MI'), ('MN', 'Minnesota MN'), ('MS', 'Mississippi MS'), ('MO', 'Missouri MO'), ('MT', 'Montana MT'), ('NE', 'Nebraska NE'), ('NV', 'Nevada NV'), ('NH', 'New Hampshire NH'), ('NJ', 'New Jersey NJ'), ('NM', 'New Mexico NM'), ('NY', 'New York NY'), ('NC', 'North Carolina NC'), ('ND', 'North Dakota ND'), ('OH', 'Ohio OH'), ('OK', 'Oklahoma OK'), ('OR', 'Oregon OR'), ('PA', 'Pennsylvania PA'), ('RI', 'Rhode Island RI'), ('SC', 'South Carolina SC'), ('SD', 'South Dakota SD'), ('TN', 'Tennessee TN'), ('TX', 'Texas TX'), ('UT', 'Utah UT'), ('VT', 'Vermont VT'), ('VA', 'Virginia VA'), ('WA', 'Washington WA'), ('WV', 'West Virginia WV'), ('WI', 'Wisconsin WI'), ('WY', 'Wyoming WY')], help_text='Jurisdiction abbreviation', max_length=10)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'diesel'), ('Gasoline', 'gasoline')], default='diesel', help_text='Fuel type (diesel by default)', max_length=20)),
                ('total_cost', models.FloatField(help_text='Cost of bought fuel')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], default='USD', help_text='Currency (US dollar by default)', max_length=5)),
                ('fuel_amount', models.FloatField(help_text='Volume of fuel bought')),
                ('fuel_unit', models.CharField(choices=[('gal', 'gallons'), ('ltr', 'liter')], default='gal', help_text='Volume measurement (gallons by default)', max_length=10)),
                ('ref_no', models.CharField(blank=True, help_text='Invoice number', max_length=15)),
                ('vendor', models.CharField(help_text='Truck stop name', max_length=40)),
                ('odometer', models.IntegerField(blank=True, help_text='Odometer reading on arrival to the truck stop')),
                ('odometer_unit', models.CharField(blank=True, choices=[('km', 'kilometers'), ('mi', 'miles')], help_text='Distance measurement', max_length=5)),
                ('driver', models.ForeignKey(help_text='Link to related the driver data', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Driver')),
                ('truck', models.ForeignKey(help_text='Link to the related unit(vehicle) data', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Unit')),
            ],
        ),
    ]
