# Generated by Django 2.2.4 on 2019-08-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20190824_1132'),
        ('Reporting', '0002_auto_20190826_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_report',
            name='truck',
            field=models.ForeignKey(help_text='Link to the related unit(vehicle) data', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.Unit'),
        ),
    ]
